$schema: ""
description: An experimental configuration sheet
properties:
  rawdatadir:
    type: string
    description: directory of patients with predefined format
  centers:
    type: array
    description: list of centers subdirectory of rawdatadir to analyze
  patient:
    type: string
    description: (optional) patient to run within this directory only

required:
  - rawdatadir